apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../components/oauth/base
  - sealedsecret.google.yaml

components:
  - ../../../../../components/oauth/overlays/google
